FROM maven:3.6.3-openjdk-11 AS build
COPY ./ /app
WORKDIR /app
RUN mvn -q --show-version --update-snapshots --batch-mode clean package

FROM adoptopenjdk:11-jre-hotspot
RUN mkdir /app
WORKDIR /app
COPY --from=build ./app/api/target/users-api-1.0.0-SNAPSHOT.jar /app
EXPOSE 8080
CMD ["java", "-jar", "users-api-1.0.0-SNAPSHOT.jar"]