apiVersion: apps/v1
kind: Deployment
metadata:
  name: uniborrow-users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uniborrow-users
  template:
    metadata:
      labels:
        app: uniborrow-users
    spec:
      containers:
        - image: lh5107/uniborrow-users:2022-01-01-20-09-04
          name: uniborrow-users
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://surus.db.elephantsql.com:5432/jsyabbvk
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: jsyabbvk
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: uniborrow-users-db-pass
                  key: password
            - name: KUMULUZEE_CONFIG_ETCD_HOSTS
              value: http://etcd:2379
            - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
              value: http://etcd:2379
            - name: KUMULUZEE_DISCOVERY_CLUSTER
              value: uniborrow-cluster
            - name: KUMULUZEE_SERVER_BASEURL
              value: http://uniborrow-users:8080
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /health/ready
              port: server
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 2
---

apiVersion: v1
kind: Service
metadata:
  name: uniborrow-users
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    app: uniborrow-users
