kumuluzee:
  name: uniborrow-users-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-location: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/UsersDB
      connection-url: jdbc:postgresql://localhost:5432/users
      username: dbuser
      password: postgres
  config:
    consul:
      agent: http://localhost:8500
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/UsersDB
admin-properties:
  restrict-users: false
  disable-users: false
  broken: false