kumuluzee:
  name: uniborrow-users-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-location: http://localhost:8080
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/UsersDB
      connection-url: jdbc:postgresql://localhost:5432/users
      username: dbuser
      password: postgres
      pool:
        max-size: 1
  config:
    etcd:
      hosts: http://localhost:2379
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
  discovery:
    etcd:
      hosts: http://localhost:2379
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/UsersDB
  metrics:
    servlet:
      enabled: true
      mapping: /metrics/*
    web-instrumentation:
      - name: metrics-endpoint
        url-pattern: /metrics/*
        status-codes: "200, 500"
      - name: users-endpoint
        url-pattern: /v1/users*
        status-codes: "200, 500"
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                            <Configuration name="comments">
                                <Appenders>
                                    <Console name="console" target="SYSTEM_OUT">
                                        <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                    </Console>
                                    <Socket name="logstash" host="8ff6c166-5030-437c-b97b-37178a04750d-ls.logit.io"
                                    port="24755" protocol="udp">
                                        <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                    </Socket>
                                </Appenders>
                                <Loggers>
                                    <!-- Default logger -->
                                    <Root level="all">
                                        <AppenderRef ref="console" level="info" />
                                        <AppenderRef ref="logstash" level="trace" />
                                    </Root>
                                </Loggers>
                            </Configuration>'
admin-properties:
  restrict-users: false
  disable-users: false
  broken: false